version: "3"
services:
  nginx:
    container_name: nginx-wordpress
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/.htpasswd:/etc/nginx/.htpasswd
      - ./etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    depends_on:
      - wordpress
    networks:
      - app-network

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mysecretpassword
      WORDPRESS_DB_NAME: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=http://localhost/phpmyadmin/
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mysecretpassword
    networks:
      - app-network

  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:latest
  #   depends_on:
  #     - nginx
  #   command: >-
  #             certonly --reinstall --webroot --webroot-path=/var/www/certbot
  #             --email ${EMAIL} --agree-tos --no-eff-email
  #             -d thefuturefuse.com
  #   volumes:
  #     - ./etc/letsencrypt:/etc/letsencrypt
  #     - ./certbot/data:/var/www/certbot
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge 

volumes:
  wordpress: